### PR TITLE
Always set -s ldflag for darwin to fix dwarf error when cross-building

### LINKED ISSUE #11: Always set -ldflags=-s for darwin
```
# darwin-amd64
rm -rf node_exporter node_exporter-0.12.0.darwin-amd64.tar.gz .build *-stamp
cd /go/src/github.com/prometheus/node_exporter && GO15VENDOREXPERIMENT=1 GOPATH=/go /usr/local/go/bin/go build -ldflags "-X main.Version=0.12.0 -X "github.com/prometheus/node_exporter"/collector.Version=0.12.0 -X "github.com/prometheus/node_exporter"/collector.Revision=dd76a68 -X "github.com/prometheus/node_exporter"/collector.Branch=master" -o node_exporter
# github.com/prometheus/node_exporter
/usr/local/go/pkg/tool/linux_amd64/link: /usr/local/go/pkg/tool/linux_amd64/link: combining dwarf failed: open /tmp/go-link-233789061/go.dwarf: no such file or directory
```

### PR DESCRIPTION
**Pull request by sdurrheimer**
Fixes #11

@grobie

### CODE REVIEW

File: cmd/build.go [hunk 1]
```diff
@@ -107,23 +117,21 @@ func getLdflags(info ProjectInfo) string {
...
 
 		err = tmpl.Execute(tmplOutput, info)
 		fatalMsg(err, "Failed to execute ldflags text/template")
 
-		if goos != "darwin" {
-			tmplOutput.WriteString("-extldflags \"-static\"")
-		}
-
-		return tmplOutput.String()
+		ldflags = append(ldflags, tmplOutput.String())
```
Comment (grobie) [inline cmd/build.go]: Is it valid to define ldflags multiple times? E.g. in case someone sets `-s` also in `.promu.yml`? Should check if `-s` and static flags are already present first?

Comment (sdurrheimer) [inline cmd/build.go]: I remember that the `go build` command doesn't complain about having the same ldflag declared multiple times (test done with `-s`). I can't say if it works with all flags tho.

Comment (sdurrheimer) [inline cmd/build.go]: @grobie I've added the verification

File: cmd/build.go [hunk 2]
```diff
@@ -107,23 +110,28 @@ func getLdflags(info ProjectInfo) string {
...
+		ldflags = append(ldflags, strings.Split(tmplOutput.String(), "\n")...)
+	} else {
+		ldflags = append(ldflags, fmt.Sprintf("-X main.Version=%s", info.Version))
+	}
 
-		return tmplOutput.String()
+	if goos == "darwin" && !stringInSlice("-s", ldflags) {
+		// Fixes dwarf error: golang/go#11994
+		ldflags = append(ldflags, "-s")
+	} else if !stringInSlice("-extldflags \"-static\"", ldflags) {
```
Comment (grobie) [inline cmd/build.go]: FYI https://golang.org/ref/spec#String_literals

    `-extldflags "-static"`

**Comment by grobie** [comment]
:+1:
