### PR TITLE
Abort crossbuild on error

### LINKED ISSUE #9: Abort crossbuild on error
The crossbuild command doesn't seem to get stopped on error

```
promu crossbuild
> running the main builder docker image
Error: Unknown option: linux/amd64 linux/386 darwin/amd64 darwin/386 windows/amd64 windows/386 freebsd/amd64 freebsd/386 openbsd/amd64 openbsd/386 netbsd/amd64 netbsd/386 dragonfly/amd64
Usage: builder.sh [args]
  -i,--import-path arg  : Go import path of the project
  -p,--platforms arg    : List of platforms (GOOS/GOARCH) to build separated by a space
  -T,--tests            : Go run tests then exit
panic: Error: Unknown option: linux/amd64 linux/386 darwin/amd64 darwin/386 windows/amd64 windows/386 freebsd/amd64 freebsd/386 openbsd/amd64 openbsd/386 netbsd/amd64 netbsd/386 dragonfly/amd64
Usage: builder.sh [args]
  -i,--import-path arg  : Go import path of the project
  -p,--platforms arg    : List of platforms (GOOS/GOARCH) to build separated by a space
 [recovered]            : Go run tests then exit
        panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x752d80, 0xc82000e120)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/prometheus/promu/vendor/github.com/progrium/go-shell.(*Process).Error(0xc820134450, 0x0, 0x0)
        /home/grobie/code/go/src/github.com/prometheus/promu/vendor/github.com/progrium/go-shell/shell.go:206 +0x25d
github.com/prometheus/promu/vendor/github.com/progrium/go-shell.ErrExit()
        /home/grobie/code/go/src/github.com/prometheus/promu/vendor/github.com/progrium/go-shell/shell.go:51 +0x181
panic(0x77f2e0, 0xc820134450)
        /usr/lib/go/src/runtime/panic.go:426 +0x4e9
github.com/prometheus/promu/vendor/github.com/progrium/go-shell.(*Command).Run(0xc82008fec0, 0x6)
        /home/grobie/code/go/src/github.com/prometheus/promu/vendor/github.com/progrium/go-shell/shell.go:173 +0x81a
github.com/prometheus/promu/vendor/github.com/progrium/go-shell.Run(0xc82006cfc0, 0x6, 0x6, 0x6c68c0)
        /home/grobie/code/go/src/github.com/prometheus/promu/vendor/github.com/progrium/go-shell/shell.go:218 +0x43
github.com/prometheus/promu/cmd.runCrossbuild()
        /home/grobie/code/go/src/github.com/prometheus/promu/cmd/crossbuild.go:123 +0xd08
github.com/prometheus/promu/cmd.glob.func3(0x99f4c0, 0x9c09b0, 0x0, 0x0)
        /home/grobie/code/go/src/github.com/prometheus/promu/cmd/crossbuild.go:54 +0x14
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).execute(0x99f4c0, 0x9c09b0, 0x0, 0x0, 0x0, 0x0)
        /home/grobie/code/go/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:569 +0x85a
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x99fac0, 0x99f4c0, 0x0, 0x0)
        /home/grobie/code/go/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:656 +0x55c
github.com/prometheus/promu/vendor/github.com/spf13/cobra.(*Command).Execute(0x99fac0, 0x0, 0x0)
        /home/grobie/code/go/src/github.com/prometheus/promu/vendor/github.com/spf13/cobra/command.go:615 +0x2d
github.com/prometheus/promu/cmd.Execute()
        /home/grobie/code/go/src/github.com/prometheus/promu/cmd/promu.go:57 +0x27
main.main()
        /home/grobie/code/go/src/github.com/prometheus/promu/main.go:20 +0x14
```

### PR DESCRIPTION
**Pull request by sdurrheimer**
Fixes #9 

@grobie

### CODE REVIEW

File: cmd/crossbuild.go [hunk 1]
```diff
@@ -125,27 +125,31 @@ func runCrossbuild() {
 
 	if mainPlatformsParam := strings.Join(mainPlatforms[:], " "); mainPlatformsParam != "" {
 		fmt.Println("> running the main builder docker image")
-		sh("docker run --rm -t -v $PWD:/app",
-			dockerMainBuilderImage, "-i", repoPath, "-p", q(mainPlatformsParam))
+		if err := docker("run --rm -t -v $PWD:/app", dockerMainBuilderImage, "-i", repoPath, "-p", q(mainPlatformsParam)); err != nil {
+			fatalMsg("The main builder docker image exited unexpectedly", err)
```
Comment (grobie) [inline cmd/crossbuild.go]: nitpicking (sorry), but let's put a `:` at the end, so that the actual error message is clearly separated? Or does this happen somewhere else?

**Comment by grobie** [comment]
Thanks! :+1: besides the error message format.

File: cmd/crossbuild.go (hunk 1 above)
Comment (sdurrheimer) [inline cmd/crossbuild.go]: Already done by the `fatalMsg()` function. https://github.com/prometheus/promu/blob/master/cmd/promu.go#L132-L135
